### ISSUE TITLE
Sentry findUserByActivationCode is missing in Sentinel

### ISSUE THREAD

**Issue by webpatser** [cartalyst/sentinel#14]
Migrating to Sentinel I am stuck in the activation process. The findUserByActivationCode method is missing in Sentinel. You can only activate an account by passing a User object. But people are not logged in when not activated.

What's the correct workflow to activate without logging in? Or should I create a Pull Request with the method ;-)

**Comment by llioor** [comment]
@webpatser  @brunogaspar  I totally agree with webpatser:
1. The users never  need to see their ID. (I don't want that the user will know how many users I have in the system + I don't want that the user will play with cookies user id and etc)
2. The code has to be unique, a quick "do while" statement will solve the issue in order to generate a unique code.
3. Index in code is something very important when you have ############ rows and big system can reach it easily.

any news about it?

**Comment by brunogaspar** [comment]
@llioor Just use whatever you need to identify the user then use that to fetch the user, simple stuff.

**Comment by feraser** [comment]
I need method Activation::complete($user, $code); returns true or false, but it doesn't return nothing, just "null" in 2 answers.
Can anyone help me?
thanks
