### ISSUE TITLE
Writing Sentinel Add-ons

### ISSUE THREAD

**Issue by renarsvilnis** [cartalyst/sentinel#171]
Hey, I'm interested in writing a Sentinel Add-on for blacklisting usernames such as `admin, user, ...`, is there any documentation for writing Add-ons?

**Comment by brunogaspar** [comment]
@renarsvilnis We don't have any documentation on writing addons on Sentinel because there's no real need to have such documentation.

For your use case, you can probably just write a simple package that will verify if the submitted username is valid or not or just listen to Sentinel events like the registering event and validate the username there.
