### ISSUE TITLE
How to implement forgot password reset and activation by sending email?

### ISSUE THREAD

**Issue by paprilia** [cartalyst/sentinel#264]
Hi, 
How can I implement forgot password reset using Sentinel in Laravel 5.2? It is better if there is something like toke with expiration time.

Is it only just update the user with the new password using Sentinel::update() ? or more than that?

Do you have any documentation regarding email activation and forgot password reset ?

Thanks

**Comment by alanondra** [comment]
For user activation, when the user registers I create an activation, then fire an event on user registration which notifies the created user with a link to an activation page. When the user goes to the activation page it uses the user ID and code to find the activation and calls complete. If all goes well I redirect the user to the login page with a success message. In 5.2 you probably have to manually create a mail message in the event listener or something.

I haven't gotten to the other bits yet, myself.

**Comment by kavin-90** [comment]
For Native version ?

**Comment by a3gz** [comment]
I built my processes based entirely on this blog: https://naomiaro.com/tag/sentinel 

@kavin-90 If you use a Native Sentinel installation (like me) you'll have  to filter all the Laravel specific code and translate it to your own environment; but once you figure out that, all the rest is essentially the same. 

Regards.

**Comment by kavin-90** [comment]
sentinel has some code which has same function like check() and getUser and guest()  for guest same check() will work and migration is easy also i fixed sentinel mysql 5.6.x sql file because it has mysql syntax error for timestamp column there was 2 column using same thing which mysql point out and said only one column can use current_timestamp

somehow i'm getting PHPSESSID cookie than sentinel cookie which i set.
