### ISSUE TITLE
Issue with [exists] method on [Activation] class not returning the expected value

### ISSUE THREAD

**Issue by zedee** [cartalyst/sentinel#268]
I'm having a hard time figuring out what is going on with this situation (steps to reproduce):

1. I Create some users via database seed.
2. In the seeder, once a user is created, I call the ```Activation::complete``` method on them, following the package documentation.
3. Checking into the database (```activations``` table), the users are apparently activated, everything seems fine until here.

The issue I'm facing is that when I do this call:
```
$user = Sentinel::findByCredentials(['login' => 'test@example.org']);
dd(Activation::exists($user);
```

the dump output is ```FALSE```

However, if I do this way:
```
$user = Sentinel::findByCredentials(['login' => 'test@example.org']);
dd(Activation::completed($user)->exists());
```

the output is ```TRUE```

What I'm missing here?

**Comment by brunogaspar** [comment]
You're doing two different calls that has different behaviour.

```php
Activation::exists($user)
```

Runs the `exists` method on the Activation repository.

```php
Activation::completed($user)->exists()
```

Runs the `exists` method on the Activation model.

**Now to explain how it works:**

The `Activation::exists` will only return `true` if there's an activation that was not activated and not expired.

While the `Activation::completed` will return `true` if the user has completed the activation or `false` if he's not activated and if you chain `exists` here, it will most of the times return `true` because the entry exists on the database, is the same as calling `$entry->exist`.

Hope it clarifies your confusion.
