### ISSUE TITLE
How migrate password from Sentry to Sentinel

### ISSUE THREAD

**Issue by rcarrascop** [cartalyst/sentinel#291]
can it be done?

**Comment by brunogaspar** [comment]
Hello,

You have 3 options:

### 1

Use the same hashing strategy that you have on Sentry on Sentinel.

### 2

First i would rename the current `password` column to be `password_old` or something like that, you'll see why below.

Now, when a user tries to login and it fails, you'll catch the error, get the submitted email and password and use the Sentry hashing strategy to verify if the user is valid, against using the `password_old` column, if it's valid you can then use Sentinel to update the user password and you can then make the `password_old` field empty for this user.

It's more and the only downside i see with this is that you'll need to have this code in place for quite some time, since not everyone

### 3

Not my favorite, but pretty much force every user to reset their passwords.
As i said it's not my favorite, but it's the easiest.

--

You can check this [Gist](https://gist.github.com/brandonferens/ee3ad68c97b589ff2798) if you haven't in case you want to import other data from Sentry to Sentinel as well.

Hope it helps.

**Comment by dzanfardino** [comment]
Hi,
I need to migrate Sentry users to Sentinel, I'm using the native Hasher, same that was used to create Sentry Users, but the check on the password fails, I've tried using the same APP_KEY, without success. 
I'm stuck, and I'd really appreciate any help

Thanks
