### ISSUE TITLE
Question about activation

### ISSUE THREAD

**Issue by atxy2k** [cartalyst/sentinel#332]
how know if one user is activated?

**Comment by PankajSanam** [comment]
You can check if a user is activated or not by using this-

$user = Sentinel::findById(1);

if (Activation::completed($user)) {
    // User account is activated
} else {
    // Not activated
}

This is clearly mentioned in the Sentinel docs.

**Comment by brunogaspar** [comment]
Yup, do as @PankajSanam mentioned.

It's covered on the documentation https://cartalyst.com/manual/sentinel/2.0#activation-completed

**Comment by atxy2k** [comment]
Yes, but what I wanted to know, was if the user had some attribute, for example:

<pre>$user->is_active</pre>

I solved it extending the User class and adding the following:

<pre>
public function getIsActivatedAttribute()
{
        $activation = Activation::completed($this);
        return !is_null($activation) && $activation!=false;
}
</pre>
Now i can use  without problems
<pre>
$user->is_activated
</pre>

**Comment by brunogaspar** [comment]
@atxy2k 

There are no such accessors due to the fact that this type of functionality can be removed/disabled and therefore, calling such accessors would be redundant :)

But you can obviously extend [Sentinel](https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel) and add this functionality to your user model.
