### ISSUE TITLE
Question : How to check if User have permission for current route ?

### ISSUE THREAD

**Issue by joginder89** [cartalyst/sentinel#353]
I have Created 2 roles (admin and datafeeder).

```php
$adminRole = Sentinel::getRoleRepository()->createModel()->create([
    'name' => 'Admin',
    'slug' => 'admin',
    'permissions' => array('admin' => 1),
]);

$datafeederRole = Sentinel::getRoleRepository()->createModel()->create([
    'name'  => 'Data Feeder',
    'slug'  => 'datafeeder',
    'permissions' => $dataFeederPermissions,
]);
```

and 

```php
$dataFeederPermissions = array(
    'user.create' => false,
    'user.update' => false,
    'user.view'   => false,
    'user.delete' => false
);
```

Now I am able to open user list page when logged in with datafeeder role user. How can I prevent user to open a route which they do not have permission. Is it good to add check in Middleware ?

I want to do something like 

```php
$action = $request->route()->getActionName();
        
if (!Sentinel::hasAccess($action))
{
    return redirect('admin/dashboard');
}

return $next($request);
```

in middleware

I do not know how to store Permissions as action names on roles.

**Comment by brunogaspar** [comment]
@joginder89 I've re formatted your OP so it's more readable and easier to understand.

In regards to your question, just store the FQCN i guess, something like:

```php
$permissions = [
    'App\Http\Controllers\Backend\DashboardController' => true,
];
```

Other solution is to use named routes instead of the FQCN.

To access it just use `$action = $request->route()->getName();` instead of `$action = $request->route()->getActionName();`.

But either way, is really up to you the way you want your application to store this information.
