### ISSUE TITLE
Single Persistence Error when changing the persistence model

### ISSUE THREAD

**Issue by LeftPinkie** [cartalyst/sentinel#381]
I am getting an error when trying to use the single persistence after changing the table name of Persistence model.

Here is the error message:
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'tst0023_neatstuff4u.persistences' doesn't exist (SQL: select * from `persistences` where `persistences`.`user_id` = 3 and `persistences`.`user_id` is not null)
```

Here is my Persistence model extension:
```
use Cartalyst\Sentinel\Persistences\EloquentPersistence ;
class AuthPersistenceModel extends EloquentPersistence {
	protected $table = 'auth__persistences' ;
}
```

Here is my settings for the persistence:
```
    'persistences' => [

//        'model' => 'Cartalyst\Sentinel\Persistences\EloquentPersistence',
        'model' => 'AuthPersistenceModel' ,
        'single' => true ,
    ],
```

It looks like it is still trying to query for the table `persistences`.  Is there any other class properties I need to set?

**Comment by 8633brown** [comment]
looking into this it looks like ```EloquentUser::$persistenceModel``` is the problem here.
from what i can see the EloquentUser persistences model is never altered to match the newly extended ```AuthPersistencesModel``` and is always set to ```EloquentPersistence```instead.  This is brought to light only when ```single``` is set to true as we then run ```IlluminatePersistenceRepository::flush``` which inturn calls for the relationship between the user and the persistance.
