### ISSUE TITLE
Sentinel::check() issue in laravel 5.4

### ISSUE THREAD

**Issue by sbnair** [cartalyst/sentinel#415]
Hi

   At certain times Sentinel::check() function is returning false and when this issues pops up i add just a test message using echo command something like this :
echo '<script language="javascript">';
         echo 'alert("Authentication 6")';
        echo  '</script>'; 
in check() function of sentinel class and this issue goes away, after some time it gets into normal state, why is this awkwardness coming up in check function, please let me know the reason ?

Thanks,
Shailesh.

**Comment by brunogaspar** [comment]
Hello @sbnair 

Without having a good way to reproduce the issue, is extremely difficult to help you figure out the problem on your application might be.

With that said, the issue can vary by being concurrent requests causing this somehow, filesystem permissions (when writing the session file), something on your application that has a wrong logic that could potentially cause this behaviour or something else.

If you're still experiencing this, do let us know and try to have a good way for us to at least try to reproduce the issue.

Thanks!

**Comment by dakshhmehta** [comment]
Hello @brunogaspar ,

Yes this is still re-producable in the following version:

Here is system info:
Laravel Version: 5.1.46 (LTS)
Sentinel version: 2.0.*

This happen when a page is being open multiple times, after what number of pages is random.
However, I manage to grab a log in middleware
and Sentinel::check returns false and getUser() returns null.

Also, I am using database driver for session.

I have already checked the throttle setting and tweak setting similar to that, removed all checkpoints, but the problem still persists.

You can reproduce this at http://tobu.ctrlshiftc.com. I am sending credentials in a personal message.

You can just login and click on "Check Availability" and "Book Now" and it will happen randomly anytime soon.

**Comment by cbj4074** [comment]
"Reproducible" *in code*.

Sure, someone can look at your site and see that this problem occurs, but until somebody can provide a concise code sample that demonstrates the problem, it's not practical to troubleshoot.

Also, given that you're using the database driver for sessions, my hunch is that you have some type of locking issue happening, which has nothing to do with Sentinel (the session drivers are implemented in Laravel).

Try switching your session driver and see if the issue still occurs.

Also, your Laravel version is pretty stale at this point; it's nearly 4 years old. If it does turn-out to be a locking issue with the database session driver itself (and not bad code on your part), there's a good chance that it's been fixed in a newer version of Laravel.
