### ISSUE TITLE
Is there a way to update a users password already encrypted?

### ISSUE THREAD

**Issue by breaktag** [cartalyst/sentinel#461]
Hello,

I have a bunch of encrypted passwords which I need to set as the password_hash for my users.

If I use `Sentinel::create()` or `Sentinel::update()` then it will encrypt the already encrypted version. 

I would like a updateRawPassword() method of some sort. Is it possible to bypass the encryption?

Thanks

**Comment by brunogaspar** [comment]
Hello @breaktag 

Not entirely following what you're asking, can you give a bit more clarification and/or perhaps a code example of the problem you're facing?

Thanks!

**Comment by breaktag** [comment]
@brunogaspar 

Something like this:

```
Sentinel::updateWithAlreadyEncryptedPassword([
   'user_id' => 1,
   'password' => '286755fad04869ca523320acce0dc6a4' 
])
```

Usually, you would do this below, and the sentinel package would automatically hash the password field before inserting it to the database. I dont want this to happen, I would like to insert a already hashed password without the package doing it for me:

```
Sentinel::update([
   'user_id' => 1,
   'password' => 'password' 
])
```

**Comment by brunogaspar** [comment]
I see.. that's not possible to do, since when it sees that you've provided a password, it will automatically hash it for you.

One solution, you can extend Sentinel by creating your own User repository that extends the base User repository, tweak the `fill` method so it doesn't hash the password and that should work. Although, during creation of a User that will not hash the password, unless you use different methods for create and update, if that's a requirement for you of course.

Or, just use the User model itself to perform the updates instead of pipping the updates through Sentinel itself.

Another solution, would be to have a setting where we could turn on/off the password hashing during create/update, though, not my preferred solution, as mentioned above, you might want to hash during create but not during update, or vice versa, so it adds a bit more complexity.

Maybe @suwardany can give his input here too.

**Comment by breaktag** [comment]
Thanks for clarification. I was thinking of by passing the Sentinel route and updating directly using my User model, so may look at doing that

Thank you

**Comment by suwardany** [comment]
Retrieving the model and manually performing the update is probably the easiest way. Don't think this is something that is needed on the core package, it is rarely needed and will possibly confuse people.

An alternative workaround would be to create a new hasher that just returns the string without hashing it and setting that whenever that update logic is needed.
