### ISSUE TITLE
Registering user with custom credentials.

### ISSUE THREAD

**Issue by tankerkiller125** [cartalyst/sentinel#94]
With Sentry I was able to set the credentials so that I had a username, email and password. I can do the same using sentinel however the username (which is the name of the column in my DB) fails to get put into the DB. It worked in Sentry but does not work in Sentinel.

**Comment by brunogaspar** [comment]
It worked on Sentry i believe because there was no `$fillable` property on the User model.

So you most likely need to update the `$fillable` on the User model to include the column you need to be saved.

You need to do this with your own model by following https://github.com/cartalyst/sentinel/wiki/Extending-Sentinel tutorial.
